language: python
python:
 - "2.7"
 - "3.3"
install:
 - pip install -U -i https://pypi.doubanio.com/simple pip setuptools wheel
 - pip install -U -i https://pypi.doubanio.com/simple pipenv
 - pip install coverage
 - pipenv install --deploy
 - "if [[ $TRAVIS_PYTHON_VERSION == 2.7* ]]; then pip install pylibmc; fi"
 - "if [[ $TRAVIS_PYTHON_VERSION == 3.3* ]]; then pip install python3-memcached; fi"
script: nosetests --with-coverage --cover-package=flask_kafka
